services:

  # =========================
  # HDFS
  # =========================

  
  namenode:
    image: apache/hadoop:3.3.6
    container_name: namenode
    hostname: namenode
    user: root
    command: ["hdfs", "namenode"]
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - namenode_data:/opt/hadoop/dfs/name
      - ./hadoop-config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ./hadoop-config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml:ro
    networks:
      - bigdata

  datanode:
    image: apache/hadoop:3.3.6
    container_name: datanode
    hostname: datanode
    user: root
    command: ["hdfs", "datanode"]
    ports:
      - "9864:9864"
    volumes:
      - datanode_data:/opt/hadoop/dfs/data
      - ./hadoop-config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ./hadoop-config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml:ro
    depends_on:
      - namenode
    networks:
      - bigdata


  # =========================
  # Spark
  # =========================

  spark-master:
    image: bitnamilegacy/spark:3.5
    container_name: spark-master
    hostname: spark-master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - HOME=/tmp
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - bigdata

  spark-worker:
    image: bitnamilegacy/spark:3.5
    container_name: spark-worker
    hostname: spark-worker
    user: root
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - HOME=/tmp
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - bigdata


  # =========================
  # Airflow Database
  # =========================

      # =========================
  # Airflow Database
  # =========================

  postgres:
    image: postgres:15
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 10
    networks:
      - bigdata

  # =========================
  # Airflow
  # =========================

  
  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    image: nyc-traffic-airflow:2.10.4
    container_name: airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
    ports:
      - "8085:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./etl_clean.py:/opt/airflow/etl_clean.py:ro
      - ./etl_clean_staging.py:/opt/airflow/etl_clean_staging.py:ro
      - ./hadoop-config:/opt/hadoop/etc/hadoop:ro
    command: >
      bash -c "
      airflow db migrate &&
      (airflow users create --username admin --password admin
      --firstname Admin --lastname User --role Admin
      --email admin@example.com || true) &&
      (airflow scheduler &) &&
      exec airflow webserver
      "
    networks:
      - bigdata

  # =========================
  # ClickHouse
  # =========================

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - bigdata
    
  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    depends_on:
      - clickhouse
    env_file:
      - ./superset/.env
    environment:
      SUPERSET_LOAD_EXAMPLES: "false"
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
    command:
      - /bin/sh
      - -c
      - |
        superset db upgrade &&
        (superset fab create-admin --username "$$SUPERSET_ADMIN_USERNAME" --firstname Admin --lastname User --email "$$SUPERSET_ADMIN_EMAIL" --password "$$SUPERSET_ADMIN_PASSWORD" || true) &&
        superset init &&
        /usr/bin/run-server.sh
    networks:
      - bigdata



# =========================
# Volumes
# =========================

volumes:
  namenode_data:
  datanode_data:
  postgres_data:
  clickhouse_data:
  superset_home:


# =========================
# Network
# =========================

networks:
  bigdata:
    driver: bridge
